apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  ports:
  - nodePort: 30702
    port: 8080
    protocol: TCP
    targetPort: 9090 # This is bascially Docker file port which we had mentioned.
  selector:
    app: hello-world-rest-api
    #version: v2 #Enable this if you want to send load to specific version.
  sessionAffinity: None
  type: LoadBalancer